### ISSUE TITLE
Should not redirect for aws.amazon.com

### ISSUE THREAD

**Issue by hansg60** [webdevnerdstuff/amazon-smile-redirect#10]
Recently the extension started redirecting aws.amazon.com.  It should not do that.  Thanks!

**Comment by webdevnerdstuff** [comment]
Is this for the Chrome extension or the Userscript?

**Comment by hansg60** [comment]
The chrome extension.  Let me clarify a little bit.  When I go to aws.amazon.com, I tap the "sign in to the console" button and it takes me to the following url.  This url is the one that the extension is incorrectly redirecting to smile.amazon.com.  The odd thing is that it doesn't seem to do it every time.

https://www.amazon.com/ap/signin?openid.assoc_handle=aws&openid.return_to=https%3A%2F%2Fsignin.aws.amazon.com%2Foauth%3Fcoupled_root%3Dtrue%26response_type%3Dcode%26redirect_uri%3Dhttps%253A%252F%252Fconsole.aws.amazon.com%252Fconsole%252Fhome%253Fnc2%253Dh_ct%2526src%253Dheader-signin%2526state%253DhashArgs%252523%2526isauthcode%253Dtrue%26client_id%3Darn%253Aaws%253Aiam%253A%253A015428540659%253Auser%252Fhomepage&openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&action=&disableCorpSignUp=&clientContext=&marketPlaceId=&poolName=&authCookies=&pageId=aws.login&siteState=registered%2CEN_US&accountStatusPolicy=P1&sso=&openid.pape.preferred_auth_policies=MultifactorPhysical&openid.pape.max_auth_age=120&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&server=%2Fap%2Fsignin%3Fie%3DUTF8&accountPoolAlias=&forceMobileApp=0&language=EN_US&forceMobileLayout=0&awsEmail=myemail)

**Comment by webdevnerdstuff** [comment]
Good catch. I'l see about integrating a fix for this situation.

In the meantime what you can do is disable the extension via the extension icon when you need to sign in.

**Comment by hansg60** [comment]
Thanks!

**Comment by webdevnerdstuff** [comment]
I just made the updates to exclude certain sites when it uses the www.amazon.com login page. The code in the repository is update, but it will take possibly a day or two before the Chrome store will publish the update. Let me know if everything works out for you when it's updated.

**Comment by webdevnerdstuff** [comment]
@hansg60 New version finally published today v2.0.3. Let me know if that works out for you.
