### ISSUE TITLE
Redirect loops on non-US amazon sites

### ISSUE THREAD

**Issue by pholvs** [webdevnerdstuff/amazon-smile-redirect#102]
**Describe the bug**
When using non-US amazon links, the browser will become stuck in a redirect loop.  Using the US page (.com) with the same URL resolves this.

Sample url: https://smile.amazon.co.uk/Cable-Matters-48Gbps-Adapter-Supporting/dp/B08MSWMXT4?pldnSite=1

**To Reproduce**
Follow link.  Reproduces with Ublock disabled or enabled.

**Expected behavior**
This could be resolved either by filtering the redirect to only happen on .com URLs or by using smile.amazon.tld

**Desktop (please complete the following information):**
 - OS: OSX 10.6 (21G115)
 - Firefox Version 106.0.1
 - Extension Version 2.2.2

**Comment by webdevnerdstuff** [comment]
It looks like Amazon made a change to something on the page that the extension uses to check if the user is logged in or not. I already have a fix in place and it will go out with the next release.

**Comment by webdevnerdstuff** [comment]
Should be fixed with the current changes. I have submitted the extension for review and it should go live as soon as Google approves the changes.

Pull Request: https://github.com/webdevnerdstuff/amazon-smile-redirect/pull/104
