### ISSUE TITLE
Only redirect when logged in not working

### ISSUE THREAD

**Issue by JojoBr0** [webdevnerdstuff/amazon-smile-redirect#103]
**Describe the bug**
If I open amazon.de when not logged in I nonetheless get redirected to smile.amazon.de

**To Reproduce**
1. Open browser with cleared cookies
2. Go to 'amazon.de'
3. Get redirect to smile.amazon.de

**Expected behavior**
I want to look product pages on amazon.de when logged out and only if I want to order something and must login, then to be redirected to smile.amazon

**Desktop**
 - OS: Windows 11
 - Browser Version: Brave 1.44 (Chromium 106)
 - Extension Version: 2.2.2

**Comment by webdevnerdstuff** [comment]
Should be fixed with the current changes. I have submitted the extension for review and it should go live as soon as Google approves the changes.

Pull Request: https://github.com/webdevnerdstuff/amazon-smile-redirect/pull/104

**Comment by JojoBr0** [comment]
After some basic tests it looks like it is working as it should now.

I will close the issue and thanks for the fast support👍
