### ISSUE TITLE
stopped redirecting on firefox dev

### ISSUE THREAD

**Issue by kinghat** [webdevnerdstuff/amazon-smile-redirect#11]
this stopped redirecting on firefox developer edition: 74.0b2 (64-bit) at https://www.amazon.com/ using the userscript version.

not sure if this is a firefox dev, amazon-smile-redirect, or violentmonkey issue as they were all updated very recently.

**Comment by webdevnerdstuff** [comment]
I assume this is for the userscript. I will check it out when I get a chance. I haven't used violentmonkey before, only greasemonkey with Firefox in the past.

**Comment by kinghat** [comment]
> I assume this is for the userscript. I will check it out when I get a chance. I haven't used violentmonkey before, only greasemonkey with Firefox in the past.

yes. sorry for not specifying. using the userscript in the violentmonkey extension.

**Comment by webdevnerdstuff** [comment]
Ok I think I see the problem. I just updated the userscript to v1.4 on OpenUserJS.org and in the repo. Please let me know if that fixed the issue.

**Comment by kinghat** [comment]
> Ok I think I see the problem. I just updated the userscript to v1.4 on OpenUserJS.org and in the repo. Please let me know if that fixed the issue.

seems to be redirecting now but its also taking me to the signin page even if im already signed in.

**Comment by webdevnerdstuff** [comment]
Updated to v1.5.

Now if you are logged in it should work. Unfortunately when logged out it goes into a redirect loop. I haven't figured out a solution for that in the Userscript yet.

**Comment by kinghat** [comment]
works when logged in. tyvm!

**Comment by webdevnerdstuff** [comment]
Just in case you are interested. I ported over the Chrome Extension into a Firefox Add-On if you are interested. It works better than the Userscript. :)

https://addons.mozilla.org/en-US/firefox/addon/amazon_smile_redirect
