### ISSUE TITLE
Redirect - no login possible with 2fa

### ISSUE THREAD

**Issue by sen1pra** [webdevnerdstuff/amazon-smile-redirect#110]
**Describe the bug**
The redirect prevents you from logging in when you receive a link via email for login confirmation.

**To Reproduce**
1. Log in from a new device / cleared cache
2. receive confirmation mail and click on link
3. redirection -> no login possible

**Expected behavior**
Should not redirect when clicking on links in (confirmation-)mails

**Comment by webdevnerdstuff** [comment]
I would need a lot more information to understand what is happening and to try to replicate it. 

Please be very detailed in every single step you take, including links of the page. 

For instance, login from a new device on what page, what are the contents of the email, when you click on the email link where does it take you, and so on. The more details I have the better I can understand the issue. Even include screenshots if possible. If there are sensitive links, just replace the sensitive parts after you see `?` in the url with fake data.

**Comment by sen1pra** [comment]
The problem seems to happen when you login at amazon with a business account. For security reasons amazon sends you an email where you need to confirm it is you. The link looks like this: https://business.amazon.de/abredir/a/c/r/*kind_of_secret_I_guess*

For me it looks like the problem is that you get redirected from one subdomain business.amazon.TLD to smile.amazon.TLD -> I guess(!) the solution should be that no redirecting takes place when you are already on a subdomain.  

Please let me know if you need further information.

**Comment by webdevnerdstuff** [comment]
I think what I can do is add that page to an excluded list of sites to redirect, and push it out with the next release. I'll try testing it out locally when I get some free time. Hopefully should have something within a week or two.

**Comment by webdevnerdstuff** [comment]
Fix added and ready to release.
https://github.com/webdevnerdstuff/amazon-smile-redirect/pull/114

**Comment by webdevnerdstuff** [comment]
Update has been submitted to Chrome/Edge/Firefox/Opera and is awaiting the review process. If you are still experiencing this issue when you have v3.0.5 installed, please let me know. Otherwise this should be resolved.
