### ISSUE TITLE
Infinite redirect

### ISSUE THREAD

**Issue by JKamsker** [webdevnerdstuff/amazon-smile-redirect#112]
Go to this site,  logged in:
https://www.amazon.com/GreenTech-0NVKD8-DC02002NS00-Battery-Latitude/dp/B089MZN8RM?pldnSite=1
Its redirecting indefinitely to the same site, again and again.

**Comment by JKamsker** [comment]
Not my main region tho. Its  usually de

**Comment by webdevnerdstuff** [comment]
I am unable to replicate this issue. (haven't tested yet by changing my region settings, but that shouldn't matter for this link). Would you please provide a more detailed work flow on how to replicate this. Browser, extension version, all steps taken (no mater how small or irrelevant it may seem), extension settings that are on/off. Make sure there are no other extensions installed with a similar functionality as well. Or if you do have another extension installed, which one is it. Basically any little detail you can think of to help me replicate the issue.

Also try clearing your cache, as well as uninstalling the extension and adding it back again.

**Comment by JKamsker** [comment]
With deactivated plugin ``https://smile.amazon.com/GreenTech-0NVKD8-DC02002NS00-Battery-Latitude/dp/B089MZN8RM?pldnSite=1`` is not available and it will redirect me back to ``https://www.amazon.com/GreenTech-0NVKD8-DC02002NS00-Battery-Latitude/dp/B089MZN8RM?pldnSite=1``

**Comment by webdevnerdstuff** [comment]
That's weird, that smile link is available for me. I used my VPN to connect to Germany, and the link still loads for me. I tried with the extension off and disabled, and the link still loads for me. 

Do you have any other Amazon related extensions installed? Not necessarily one that has the same functionality as mine. Also please try temporarily disabling all extensions to see if the redirect still happens.

**Comment by JKamsker** [comment]
No it still does it on an alt browser profile with just amazon redirect

**Comment by webdevnerdstuff** [comment]
> With deactivated plugin https://smile.amazon.com/GreenTech-0NVKD8-DC02002NS00-Battery-Latitude/dp/B089MZN8RM?pldnSite=1 is not available and it will redirect me back to https://www.amazon.com/GreenTech-0NVKD8-DC02002NS00-Battery-Latitude/dp/B089MZN8RM?pldnSite=1

If you are not logged in, Amazon has it's own redirect that takes you to the regular `www` site. So with the extension deactivated it would redirect from `smile` to `www` for any product. So this is the default behavior of the Amazon site.

As for the original link you gave, I'm really not sure what the exact issue is as I have not been able replicate it. I have tried multiple browsers, sessions, us/de/uk sites, and on another computer, and used my VPN to change my region. They all load that smile page for me and stay there with the extension enabled and when logged in. I'm somewhat out of ideas at this point on how to replicate the problem, as something is telling your Amazon site that the product doesn't exist on the smile site for some unknown reason (as it does exist for me).

Every time I go to:
`https://www.amazon.com/GreenTech-0NVKD8-DC02002NS00-Battery-Latitude/dp/B089MZN8RM?pldnSite=1` 

It takes me to this smile link and stays there:
`https://smile.amazon.com/GreenTech-0NVKD8-DC02002NS00-Battery-Latitude/dp/B089MZN8RM?pldnSite=1&ref_=nav_custrec_signin`

Is there any other links that it does this for you? Is this something that happens often?

**Comment by webdevnerdstuff** [comment]
I will be closing this issue as unfortunately Amazon has decided to end their AmazonSmile program as of Feb 20th, 2023, which will make this extension no longer useful.

https://www.aboutamazon.com/news/company-news/amazon-closing-amazonsmile-to-focus-its-philanthropic-giving-to-programs-with-greater-impact
