### ISSUE TITLE
No forwarding to Smile site from Amazon UK

### ISSUE THREAD

**Issue by adamski-again** [webdevnerdstuff/amazon-smile-redirect#45]
**No longer forwarding when using Amazon UK**
If I visit a page on Amazon UK, including the homepage, the extension does not intervene, and I remain on the main site.

**To Reproduce**
1. Go to 'https://www.amazon.co.uk/'
2. No forwarding occurs

*Desktop (please complete the following information):**
 - OS: Windows
 - Chrome Version: Version 83.0.4103.97 

**Additional context**
If you need more, drop me a line.

**Comment by webdevnerdstuff** [comment]
I am unable to replicate the issue. Let's try a couple things to see if we can get it working for you. Check after each step if it works correctly. If one works, then great, if it doesn't then move onto the next.

**1. Uninstall the Extension and reinstall it again.**
Current version 2.0.6. 
The next update 2.0.9 is pending review by Chrome. Should be some time today I think as they are pretty quick.

**2. Update Chrome to the latest version.** 
Current Version 83.0.4103.106 (as of the time of this post)

**3. Clear the browser Cache**

**4. If that doesn't work, can you try the [Firefox Extension](https://addons.mozilla.org/en-US/firefox/addon/amazon_smile_redirect/) to see if it works in that browser?


Let me know if any of those work.

**Comment by adamski-again** [comment]
A simple reinstall of the extension did it. Should really have tried that first! 🙄 Apologies for the trouble and thank you for your time. 

Adam

+44 7724724540
Typed on a phone

**Comment by webdevnerdstuff** [comment]
No problem. I'm glad you got it working. :)
