### ISSUE TITLE
Not redirecting

### ISSUE THREAD

**Issue by GirlFriday715** [webdevnerdstuff/amazon-smile-redirect#48]
I added the Amazon smile redirect to my chrome browser.  When I click on it, I see a drop down list.  First thing is it's enabled. The second item is the actual words Amazon Smile. Then followed by About, Developer, Support

My issue is that I have to click this icon twice for it to actually take me to amazon.  If it's supposed to be a redirect, why do I have to click once, then choose the drop down and click it again?

I should just be able to click on the icon and immediately go to my amazon smile.  And yes, I'm signed into amazon smile.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Windows]
 - Chrome Version [e.g. 22]

**Additional context**

**Comment by webdevnerdstuff** [comment]
That is not how the extension works. The way it works is that when you visit a page on the regular amazon.com site, it will automatically redirect you to the corresponding Amazon Smile page. You should never need to go to the extensions menu for this functionality. :) 

For example click on this link: https://www.amazon.com/LEGO-Star-Wars-Skywalker-Millennium/dp/B07Q2TQ48F

It should first load the Amazon page, then it checks to see if you are logged in by looking for the "Hello. Bob" (or whatever your name is, doesn't matter it looks for 'Hello.' )in the "Accounts & Lists" menu. If you are not logged in it will take you to Amazon Smile's login page (needs to do this to work correctly), then when you login it takes you to the page you were trying to visit. If you are logged in, it will just take you to the Amazon Smile page.

I hope that helps explain it better. :)
