### ISSUE TITLE
amazon.de sends me in a redirect loop

### ISSUE THREAD

**Issue by mplatt** [webdevnerdstuff/amazon-smile-redirect#49]
When I open a page on amazon.de I'm sent in a redirect loop

**To Reproduce**
1. https://www.amazon.de/gp/aw/ls?ref%5F=navm%5Fftr%5Fwl&pldnSite=1

**Expected behavior**
Page loads fully

**Desktop (please complete the following information):**
 - OS: Mac
 - Chrome Version Version 85.0.4183.83 (Official Build) (64-bit)

**Comment by mplatt** [comment]
[Screen Recording 2020-09-04 at 21.33.39.mov.zip](https://github.com/webdevnerdstuff/amazon-smile-redirect/files/5176830/Screen.Recording.2020-09-04.at.21.33.39.mov.zip)

**Comment by webdevnerdstuff** [comment]
I am able to replicate the issue. It seems to be something specific to the German site as I'm not able to replicate it on the US or UK sites. My guess is Amazon changed something recently.

I'll have to do some digging on this one, as nothing sticks out to what is causing this.

**Comment by webdevnerdstuff** [comment]
Next update of version 2.0.10 should fix the issue. The extension is currently waiting in the Chrome store for approval before published.
