### ISSUE TITLE
Smile Redirect Should Ignore Watch Party Links

### ISSUE THREAD

**Issue by Mr-Ison** [webdevnerdstuff/amazon-smile-redirect#53]
**Describe the bug**
There's a relatively new feature on Amazon's site called watch party that allows users to invite others to watch an Amazon Prime Video together.  Users receive a link that they can give to others and when clicked it will take you to a watch party.  Clicking on a watch party link doesn't work while Smile Redirect is enabled, it will instead take you to the watch party faq. [https://smile.amazon.com/adlp/watchparty](url)

**To Reproduce**
1. Have a friend create a watch party link
2. Click on that watch party link
3. You will see that you get redirected to the watch party faq instead of joining the watch party.

**Expected behavior**
What should happen is that you will be asked to enter your name after joining the watch party.  Then you and the host should both be able to watch a prime video together.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Firefox Version 82.0.3

**Comment by webdevnerdstuff** [comment]
I'll see about adding that url to the list of excluded pages to redirect.

**Comment by webdevnerdstuff** [comment]
Update (v2.0.11) has been submitted to Firefox and pending their review. Once it updates, if you are still have issue please let me know. Thank you.
