### ISSUE TITLE
Extension breaks Amazon Business invite acceptance

### ISSUE THREAD

**Issue by kyle0440** [webdevnerdstuff/amazon-smile-redirect#54]
**Describe the bug**
Redirection on login pages causes the Amazon Business registration process to break.

**To Reproduce**
1. User starts signed out of Amazon
2. User receives an Amazon Business invitation and clicks
3. User is taken to the registration page, but is then redirected away to an AmazonSmile login page which does not support this functionality. 

OR

1. User starts signed in to Amazon.
2. User receives an Amazon Business invitation and clicks
3. User is taken to the accept invite page, but is then redirected away to AmazonSmile, which does not support this functionality. 

**Expected behavior**
The extension should not attempt to redirect on login or registration pages. 

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by webdevnerdstuff** [comment]
What are the links for the "registration page" as well as the "accept invite page"? I can see about add them to the list of excluded pages that should not redirect.

I think this is one of the links:
https://www.amazon.com/business/register/org/landing

**Comment by kyle0440** [comment]
Things that appear to be unique IDs I have [removed]

The URL in the email: 

https://www.amazon.com/gp/f.html?C=[removed]&M=[removed]&R=[removed]=C&U=https%3A%2F%2Fwww.amazon.com%2Fab%2Finvite%2Fredirect%[removed]%3Fref%3Db2b_reg_email_newcustomer%2Fref%3[removed]_b2b_reg_email_newcustomer&H=[removed]&ref_=pe_[removed]_b2b_reg_email_newcustomer

If an account exists with the invited email already, you are brought to a sign in page with this URL: 

https://www.amazon.com/ap/signin?openid.pape.preferred_auth_policies=Singlefactor&openid.pape.max_auth_age=0&openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fab%2Finvite%2Faccount-setup%2Fget-started%3Fref_%3Dab_reg_notag_pp_gs_ab_reg_dsk%26invitationId%[removed]&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=ab_reg_us&openid.mode=checkid_setup&marketPlaceId=[removed]&language=en_US&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&pageId=amzn_business_inv_website&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&ref_=ab_reg_notag_pp_ap-sn_ab_reg_dsk&email=[removed]&switch_account=signin&disableLoginPrepopulate=1

If an account does not exist, you are brought to this registration page: 

https://www.amazon.com/ap/register?openid.pape.preferred_auth_policies=Singlefactor&openid.pape.max_auth_age=0&openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fab%2Finvite%2Faccount-setup%2Ffinish%3Fref_%3Dab_reg_notag_ul_up_ab_reg_dsk%26invitationId%[removed]&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=ab_reg_us&openid.mode=checkid_setup&marketPlaceId=[removed]&language=en_US&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&pageId=amzn_business_inv_website&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&ref_=ab_reg_notag_ul_ap-ca_ab_reg_dsk&email=[removed]

I would guess excluding /ap/signin and /ap/register would do it.

**Comment by webdevnerdstuff** [comment]
Update (v2.0.11) has been submitted to Chrome and pending their review. Once it updates, if you are still have issue please let me know. Thank you.
