### ISSUE TITLE
[Feature-Request] - choose sites manually

### ISSUE THREAD

**Issue by me1337me** [webdevnerdstuff/amazon-smile-redirect#72]
Hello,
I really like this addon! 
But it would be great to enable/disable it for some amazon urls. For instance only on amazon.de because it redirects me even if i open a link to just browse some warehousedeals on .co.uk. 
Thanks a lot!

**Comment by webdevnerdstuff** [comment]
Thank you for the feedback. Currently there is no plan to have a disabled button for each of the different sites as it's not a very common use case. The best option would be to just disable the extension when viewing one site, and turn it on for the other.
