### ISSUE TITLE
Great Job

### ISSUE THREAD

**Issue by meeDamian** [webdevnerdstuff/amazon-smile-redirect#89]
**You can close this issue as soon as you read it.**  I just wanted to say this is probably the first time I read through the code so nice, tidy, well organized, minimal, and kept left, that I was grinning all the time reading through it 😁 .

So one could say… it redirected my mood to a… _smile_ 😁 .

funfact: I thought I had a single suggestion, but then I realized it's a toggle, not a backfill as I initially misunderstood it 😅 .

~The only thing I could even suggest improving is changing these [background.js#L78](https://github.com/webdevnerdstuff/amazon-smile-redirect/blob/a247a7b90af08601c5acb0f2743379962a6c1870/src/assets/js/background.js#L78) & [background.js#L89](https://github.com/webdevnerdstuff/amazon-smile-redirect/blob/a247a7b90af08601c5acb0f2743379962a6c1870/src/assets/js/background.js#L89) to sth like:~

```js
// ignore
if (extensionStatus !== 'enabled') {
	extensionStatus = 'disabled'
}
```

~as I feel it would express the intention slightly better.~

**Comment by webdevnerdstuff** [comment]
Thank you. :)
