### ISSUE TITLE
breaks Amazon shopping profile PIN entry

### ISSUE THREAD

**Issue by fiafied** [webdevnerdstuff/amazon-smile-redirect#95]
**Describe the bug**
breaks Amazon shopping profile access with profile PIN configured. the PIN entry screen might not work with the `smile` subdomain

**To Reproduce**
steps to reproduce the behavior:
1. set PIN for Amazon shopping profile
2. enable Amazon Smile add-on
3. go to Amazon, Account, Your Profile, then select the primary profile
4. prompts for password, prompts for PIN, then returns to Your Profile selection page without ever displaying the primary profile as selected. this repeats as many times as the primary profile is selected

**Expected behavior**
the Amazon Smile redirect might need to be disabled for login or shopping profile pages

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 21H2
 - Firefox Version: 101.0.1
 - Extension Version 2.2.1

**Comment by webdevnerdstuff** [comment]
I'm not too familiar with the profiles and pin. Let me see if I'm understanding this correctly. I assume this is for the US site? I'm also not away of the shopping profiles you are talking about. Are you talking about managing the Household, or Prime Video profiles? These are the steps I took.

## Without Household Accounts:
**Steps**

1. First I went to the main menu and selected "Account"
    1. Goes to: `https://smile.amazon.com/gp/css/homepage.html?ref_=nav_AccountFlyout_ya`
2. I then selected the "Your Profiles" tile.
    1. Goes to: `https://smile.amazon.com/manage-your-profiles/home?ref_=ya_manage_your_profiles?ref_=ya_your_profile_rich-card`

The next step I'm not sure about as there's nothing that says "Primary' on it. On this page I have two profiles. One with my name (account holder), and another is "Kids".  I assume you mean account holder.

1. I select the profile with my name
    1. Goes to: `https://www.amazon.com/manage-your-profiles/profile`
    2. Extension redirects to `https://smile.amazon.com/manage-your-profiles/profile`
2. In the "Settings" area I click on the edit icon next to "PIN"
    1. Goes to: `https://www.amazon.com/ap/cvf/profile/request?requestToken=...`
3. This page now is at the "PIN assistance", where I can select "continue" for it to send me a OTP.
4. I click on continue
    1. Goes to: `https://www.amazon.com/ap/cvf/profile/verify`
5. I enter my OTP.
    1. Goes to: `https://www.amazon.com/a/c/pincollection?uiInput=...`
6. It asks me to create my PIN
7. I enter my PIN
8. It asks me to confirm the PIN
9. I enter my PIN again to confirm
    1. Goes to: `https://www.amazon.com/manage-your-profiles/profile?showMessage=update_pin_success&enrollmentContext=...`
    2. Extension redirects to: `https://smile.amazon.com/manage-your-profiles/profile?showMessage=update_pin_success&enrollmentContext=...`

## With Household Accounts
**Steps**
1. I select the profile with my name
    1. Goes to: `https://smile.amazon.com/manage-your-profiles/home?ref_=ya_manage_your_profiles?ref_=ya_your_profile_rich-card`
2. I select the main account (account holder)
    1. Goes to: `https://www.amazon.com/a/c/pinverification?uiInput=...`
3. It asked for my PIN and I entered it
    1. Goes to: `https://www.amazon.com/manage-your-profiles/profile?showMessage=update_pin_success&enrollmentContext=...`
    2. Extension redirects to: `https://smile.amazon.com/manage-your-profiles/profile`

This is where I'm not sure about the issue you are experiencing. What do you mean by it doesn't display the primary profile as selected?

**Comment by fiafied** [comment]
I mean the account holder Household Account, correct

everything was working fine before I created a PIN, but now that I have one, I see the issue described

1. I go to `https://smile.amazon.com/manage-your-profiles/home` and see a page titled "Manage your Profiles" with my account holder name, Guest, and Kids profiles listed
2. I click on the account holder
3. it loads `https://www.amazon.com/a/c/pinverification?...`, then quickly redirects to `https://smile.amazon.com/ap/signin?...` automatically without me doing anything. on `pinverification` I briefly see the PIN entry page before it auto-redirects. on `signin` where I end up once it finishes redirecting, I see a password prompt
4. I type my password and click Sign-In
5. it loads `https://smile.amazon.com/a/c/pinverification?...`. it looks like the same PIN entry page that appeared initially, but it doesn't auto-redirect somewhere else without me doing anything this time. one difference I see is that the first request URL was `www`, while this time the request URL is `smile`
6. I enter my PIN
7. it loads `https://www.amazon.com/manage-your-profiles/home`, then quickly redirects to `https://smile.amazon.com/manage-your-profiles/home` automatically. it shows me the same page titled "Manage your Profiles", taking me back to step 1

so it never takes me to `https://www.amazon.com/manage-your-profiles/profile` or `https://smile.amazon.com/manage-your-profiles/profile`, preventing me from changing my profile settings

it just keeps looping back around to profile selection, password prompt, PIN prompt, profile selection, password prompt, PIN prompt, etc.

**Comment by webdevnerdstuff** [comment]
I'm unable to recreate the issue you are experiencing. So the next best thing I can do is just add the page to the excluded sites list so it won't redirect there. I have submitted the update to Chrome, Firefox, Edge, and Opera to be approved and published. It will be in version 2.2.2.

Pull Request https://github.com/webdevnerdstuff/amazon-smile-redirect/pull/96

**Comment by fiafied** [comment]
thanks!
