### ISSUE TITLE
Redirect issues when using Firefox extension on Android

### ISSUE THREAD

**Issue by shbach** [webdevnerdstuff/amazon-smile-redirect#97]
**Describe the bug**
It is possible to use any Firefox extension on Android [by using collections in the nightly version](https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/). Currently though, when I enable this extension on my phone, it constantly redirects to log in when already logged in. When I set the option to redirect only when logged in, it won't redirect to smile.amazon.com when logged in.

**To Reproduce**
1. Install Firefox extension on Android via [collections in the nightly version](https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/)
2. Go to Amazon.com
3. See error

**Expected behavior**
Should not redirect to login when already logged in and should redirect to smile.amazon.com

**Comment by webdevnerdstuff** [comment]
I was on holiday last month. I'll take a look at this as soon as I get settled back in.

**Comment by webdevnerdstuff** [comment]
@shbach I tried playing around with the Firefox nightly version, but couldn't figure out how to install my extension, even after looking at the documentation. If I have a hard time figuring it out, I doubt the average user would be able to.

I think when it comes down to it, very few users are using a browser to shop on Amazon on their mobile phones, and are more likely to use the official Amazon app (which can be set to use AmazonSmile). So I don't think I'm going to really try to find a solution for this, but thank you for bringing this up as I didn't know the nightly build could install addons.

**Comment by e-t-l** [comment]
@shbach You may be able to get this functionality by installing it as a userscript from https://openuserjs.org/scripts/mscarchilli/Amazon_Smile_Redirect. You can install userscripts by first adding the [USI extensions](https://addons.mozilla.org/en-US/firefox/addon/userunified-script-injector/) to your Nightly collection

**Comment by webdevnerdstuff** [comment]
@e-t-l That's actually my old Userscript, it's pretty outdated now and has the redirect loop issue, so I'm not sure how good it would be to use it. But it's nice to see people know about it. :)

**Comment by shbach** [comment]
> @shbach You may be able to get this functionality by installing it as a userscript from https://openuserjs.org/scripts/mscarchilli/Amazon_Smile_Redirect. You can install userscripts by first adding the [USI extension](https://addons.mozilla.org/en-US/firefox/addon/userunified-script-injector/) to your Nightly collection

Thanks for tip. I actually ended up using a different extension that I found also works on Firefox mobile. Maybe it can be helpful to others if they specifically want mobile support. https://github.com/Aaron-P/SmartAmazonSmile

**Comment by webdevnerdstuff** [comment]
@shbach Sorry but I have removed the link to the other extension. It's technically a competitor's extension which I do not allow to be promoted here. I hope you understand. Nothing personal.

But I am curious, why do you use the Firefox Nightly build to shop on Amazon? I've never heard of anybody doing this, as almost everybody just uses the Amazon app. If this is something that more people might do in the future, I'd be more willing to look into it a little bit more. I wasn't able to figure out how to get the Extension to even add to the Firefox Nightly Build on my Android. It would be harder to debug as well.

**Comment by shbach** [comment]
> @shbach Sorry but I have removed the link to the other extension. It's technically a competitor's extension which I do not allow to be promoted here. I hope you understand. Nothing personal.
> 
> But I am curious, why do you use the Firefox Nightly build to shop on Amazon? I've never heard of anybody doing this, as almost everybody just uses the Amazon app. If this is something that more people might do in the future, I'd be more willing to look into it a little bit more. I wasn't able to figure out how to get the Extension to even add to the Firefox Nightly Build on my Android. It would be harder to debug as well.

In general I don't install apps on my phone if the website provides all the functionality I need. I use the nightly build of Firefox on Android as it's the only way to install certain other extensions I want to use since the non-nightly build only has a limited list of extensions available.

You need to create your own custom collection, add the extension to it, and then point Firefox to the collection. The link I provided in my original post gives specific instructions on how to do this.
