### ISSUE TITLE
Co Op? 

### ISSUE THREAD

**Issue by chavenor** [webdevnerdstuff/amazon-smile-redirect#99]
I'm looking to re-create the experience around the Amazon Smile browser app and was wondering if you would be open to exploring this concept.

chavenor at gmail.com

**Comment by webdevnerdstuff** [comment]
If you have any specific ideas you are thinking of, please add a post on the [Discussions](https://github.com/webdevnerdstuff/amazon-smile-redirect/discussions) page with your thoughts and ideas. Alternatively you can also contact me at [webdevnerdstuff@gmail.com](mailto:webdevnerdstuff@gmail.com).
